name: untitled
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  get_storage: ^2.0.3
  get: ^4.3.8
  flutter_local_notifications: ^8.2.0
  flutter_native_timezone: ^2.0.0
  intl: ^0.17.0
  google_fonts: ^2.3.1
  date_picker_timeline: ^1.2.3
  sqflite: ^2.0.0+4
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  rxdart: ^0.27.2
  provider: ^6.0.0
  charts_flutter: ^0.12.0
  pie_chart: ^4.0.1
  path: ^1.6.2
  path_provider: ^2.0.9
  datetime_picker_formfield: ^1.0.0
  curved_navigation_bar: ^1.0.3
  liquid_swipe: ^2.1.1
  awesome_dialog: ^2.1.3
  smooth_page_indicator: ^1.0.0+2
  sliding_up_panel: ^2.0.0+1
  shared_preferences: ^2.0.13
  http: ^0.13.4
  image_picker: ^0.8.5
  string_stats: ^0.0.3
  flutter_staggered_grid_view: ^0.4.1
  share: ^2.0.4
  lottie: ^1.2.1
  confetti: ^0.5.4+1
  alert_dialog: ^1.0.1
  bloc: ^8.0.3
  sleek_circular_slider: ^2.0.1
  flutter_bloc: ^8.0.1
  cached_network_image: ^3.0.0
  expandable: ^5.0.1
  pedometer: ^3.0.0
  analog_clock:




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.4

flutter_icons:
  android: true
  ios: true
  image_path: "img/appicon.jpeg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - img/appicon.jpeg
      - img/todo.png
      - img/Journey-cuate.png
      - img/habit.png
      - img/time.png
      - img/article.png
      - img/logo.png
      - img/add.svg
      - img/drink.png
      - img/wealth.png
      - img/grade.png
      - img/blog.png
      - images/profile.jpg
      - images/background.jpg
      - images/note.json
      - assets/smile.png
      - assets/sad.png
      - assets/angry.png
      - assets/scared.png
      - assets/surprised.png
      - assets/loving.png
      - assets/sports.png
      - assets/sleeping.png
      - assets/shop.png
      - assets/relax.png
      - assets/reading.png
      - assets/movies.png
      - assets/gaming.png
      - assets/friends.png
      - assets/family.png
      - assets/excercise.png
      - assets/eat.png
      - assets/date.png
      - assets/clean.png






  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
      - family: NimbusSanL
        fonts:
          - asset: fonts/NimbusSanL-Bol.otf
            weight: 700
          - asset: fonts/NimbusSanL-RegIta.otf
            style: italic
      - family: OpenSans
        fonts:
          - asset: fonts/OpenSans-Bold.ttf
            weight: 700
          - asset: fonts/OpenSans-Regular.ttf
            weight: 400
          - asset: fonts/OpenSans-Light.ttf
            weight: 300
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
